version: '3'
services:
  simple-go-server-api:
    build:
      context: .
    depends_on:
      - simple-go-server-db
    expose:
      - 8010
    ports:
      - '8010:8010'
    environment:
      - APP_DB_USERNAME=postgres
      - APP_DB_NAME=postgres
      - APP_DB_PASSWORD=mysecretpassword
      - APP_DB_HOST=simple-go-server-db
      - APP_DB_PORT=5432
      - APP_DB_SSLMODE=disable 
  simple-go-server-db:
    image: postgres
    expose:
      - 5432
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
    # logging:
    #   driver: none
